background = 1a1a1a
foreground = ffefe8
cursor-color = ffefe8

selection-foreground = ffffff
selection-background = 6f6f6f

palette = 0=#1a1a1a
palette = 1=#6f5557
palette = 2=#6a645d
palette = 3=#856b6c
palette = 4=#927e78
palette = 5=#9c807c
palette = 6=#968d8b
palette = 7=#ffefe8
palette = 8=#6f6f6f
palette = 9=#8a6a6c
palette = 10=#847d74
palette = 11=#a68587
palette = 12=#b69d96
palette = 13=#c3a09b
palette = 14=#bbb0ad
palette = 15=#ffffff
