background = 131514
foreground = ffffff
cursor-color = ffffff

selection-foreground = ffffff
selection-background = 515b55

palette = 0=#131514
palette = 1=#664e49
palette = 2=#6d6869
palette = 3=#9b7d79
palette = 4=#948384
palette = 5=#958582
palette = 6=#99918e
palette = 7=#ffeee8
palette = 8=#515b55
palette = 9=#7f615b
palette = 10=#888283
palette = 11=#c19c97
palette = 12=#b9a3a5
palette = 13=#baa6a2
palette = 14=#bfb5b1
palette = 15=#ffffff
