cursor                  #ffeee8
cursor_text_color       #ffffff

foreground              #ffeee8
background              #131514
selection_foreground    #ffffff
selection_background    #515b55
url_color               #948384

color0   #131514
color8   #515b55

color1   #664e49
color9   #7f615b

color2   #6d6869
color10  #888283

color3   #9b7d79
color11  #c19c97

color4   #948384
color12  #b9a3a5

color5   #958582
color13  #baa6a2

color6   #99918e
color14  #bfb5b1

color7   #ffeee8
color15  #ffffff
