# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#0a0a03\033\\"
printf "\033]4;1;#262118\033\\"
printf "\033]4;2;#675143\033\\"
printf "\033]4;3;#5d5e5a\033\\"
printf "\033]4;4;#8e8970\033\\"
printf "\033]4;5;#b49c7d\033\\"
printf "\033]4;6;#bab69d\033\\"
printf "\033]4;7;#ffffe2\033\\"
printf "\033]4;8;#2a2b10\033\\"
printf "\033]4;9;#2f291e\033\\"
printf "\033]4;10;#806553\033\\"
printf "\033]4;11;#747570\033\\"
printf "\033]4;12;#b1ab8c\033\\"
printf "\033]4;13;#e1c39c\033\\"
printf "\033]4;14;#e8e3c4\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#0a0a03\033\\"

# Foreground
printf "\033]10;#ffffff\033\\"

# Cursor
printf "\033]12;#ffffff\033\\"

# Border
printf "\033]7044;#ffffff\033\\"
