# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#1e1d14\033\\"
printf "\033]4;1;#7e6860\033\\"
printf "\033]4;2;#8c7f74\033\\"
printf "\033]4;3;#97856c\033\\"
printf "\033]4;4;#92938f\033\\"
printf "\033]4;5;#9d9d99\033\\"
printf "\033]4;6;#afaf9d\033\\"
printf "\033]4;7;#fefce0\033\\"
printf "\033]4;8;#807956\033\\"
printf "\033]4;9;#9d8278\033\\"
printf "\033]4;10;#af9e91\033\\"
printf "\033]4;11;#bca687\033\\"
printf "\033]4;12;#b6b7b2\033\\"
printf "\033]4;13;#c4c4bf\033\\"
printf "\033]4;14;#dadac4\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#1e1d14\033\\"

# Foreground
printf "\033]10;#ffffff\033\\"

# Cursor
printf "\033]12;#ffffff\033\\"

# Border
printf "\033]7044;#ffffff\033\\"
