# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#131514\033\\"
printf "\033]4;1;#664e49\033\\"
printf "\033]4;2;#6d6869\033\\"
printf "\033]4;3;#9b7d79\033\\"
printf "\033]4;4;#948384\033\\"
printf "\033]4;5;#958582\033\\"
printf "\033]4;6;#99918e\033\\"
printf "\033]4;7;#ffeee8\033\\"
printf "\033]4;8;#515b55\033\\"
printf "\033]4;9;#7f615b\033\\"
printf "\033]4;10;#888283\033\\"
printf "\033]4;11;#c19c97\033\\"
printf "\033]4;12;#b9a3a5\033\\"
printf "\033]4;13;#baa6a2\033\\"
printf "\033]4;14;#bfb5b1\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#131514\033\\"

# Foreground
printf "\033]10;#ffffff\033\\"

# Cursor
printf "\033]12;#ffffff\033\\"

# Border
printf "\033]7044;#ffffff\033\\"
