set -g status-style "bg=default,fg=#ffeee8"
set -g message-style "bg=#b9a3a5,fg=#131514,bold"
set -g mode-style "bg=#c19c97,fg=#131514,bold"
set -g pane-border-style "fg=#515b55"
set -g pane-active-border-style "fg=#b9a3a5"
setw -g window-status-activity-style "default"
setw -g window-status-bell-style "default"
set -g @window-pill-normal-left "#[fg=#515b55,bg=default]#[fg=#ffeee8,bg=#515b55]"
set -g @window-pill-normal-right "#[fg=#515b55,bg=default]"
set -g @window-pill-activity-left "#[fg=#888283,bg=default]#[fg=#131514,bg=#888283,bold]"
set -g @window-pill-activity-right "#[fg=#888283,bg=default]"
set -g @window-pill-bell-left "#[fg=#7f615b,bg=default]#[fg=#131514,bg=#7f615b,bold]"
set -g @window-pill-bell-right "#[fg=#7f615b,bg=default]"
set -g status-left "#[fg=#b9a3a5,bg=default]#[fg=#131514,bg=#b9a3a5,bold] 󱂬 #S #[fg=#b9a3a5,bg=#515b55]#[fg=#ffeee8,bg=#515b55] 󰒋 #H #[fg=#515b55,bg=default]"
set -g status-right "#{?client_prefix,#[fg=#7f615b,bg=default]#[fg=#131514,bg=#7f615b,bold] 󰘳 PREFIX #[fg=#7f615b,bg=default] ,}#{?pane_in_mode,#[fg=#c19c97,bg=default]#[fg=#131514,bg=#c19c97,bold] 󰆏 COPY #[fg=#c19c97,bg=default] ,}#{?window_zoomed_flag,#[fg=#888283,bg=default]#[fg=#131514,bg=#888283,bold] 󰁌 ZOOM #[fg=#888283,bg=default] ,}#(sh \"$HOME/.config/tmux/battery-segment.sh\" \"default\" \"#515b55\" \"#ffeee8\")#(sh \"$HOME/.config/tmux/now-playing-segment.sh\" \"default\" \"#99918e\" \"#131514\" \"#b9a3a5\" \"#131514\")"
setw -g window-status-format "#{?window_bell_flag,#{@window-pill-bell-left},#{?window_activity_flag,#{@window-pill-activity-left},#{@window-pill-normal-left}}}#{?window_activity_flag, 󱅫,}#{?window_bell_flag, 󰂞,} #I #W #{?window_bell_flag,#{@window-pill-bell-right},#{?window_activity_flag,#{@window-pill-activity-right},#{@window-pill-normal-right}}}#[default]"
setw -g window-status-current-format "#[fg=#c19c97,bg=default]#[fg=#131514,bg=#c19c97,bold]#{?window_activity_flag, 󱅫,}#{?window_bell_flag, 󰂞,} #I #W#{?window_zoomed_flag, 󰁌,} #[fg=#c19c97,bg=default]#[default]"
