# Generated by hellwal

set wallpaper '/Users/moy/Google Drive/My Drive/[02]Moy/[03]PC/[01]Wallpapers/[31]CSM/processed/wallhaven-jx3xv5.jpg'

set background '0a0a03'
set foreground 'ffffff'
set cursor 'ffffff'
set border 'ffffff'

set color0 '0a0a03'
set color1 '262118'
set color2 '675143'
set color3 '5d5e5a'
set color4 '8e8970'
set color5 'b49c7d'
set color6 'bab69d'
set color7 'ffffe2'
set color8 '2a2b10'
set color9 '2f291e'
set color10 '806553'
set color11 '747570'
set color12 'b1ab8c'
set color13 'e1c39c'
set color14 'e8e3c4'
set color15 'ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="$LS_COLORS:su=30;41:ow=30;42:st=30;44:"
