alias chmox='chmod +x'
alias cp='cp -v'
alias diskspace_report='df --si /'
alias dotfiles='subl ~/code/dotfiles'
alias grep='command grep --color=auto'
alias hosts='sudo ${EDITOR:-nvim} /etc/hosts'
alias la='lsd -F --group-directories-first -Al'
alias li='lighthouse'
alias ls='lsd -F --group-directories-first -A'
alias lperf='lighthouse --only-categories=performance'
alias push='git push'
alias resetmouse=$'printf "\\e[?1000l"'
alias rm='rm -v'
alias signaldone='printf "done\n" > /tmp/done_pipe'
alias sorteduniq='sort | uniq -c | sort --reverse --ignore-leading-blanks --numeric-sort'
alias sorteduniq-asc='sort | uniq -c | sort --ignore-leading-blanks --numeric-sort'
alias ungz='gunzip -k'
alias waitfordone='mkfifo /tmp/done_pipe 2>/dev/null || true; read -r _ < /tmp/done_pipe'
alias watchexec='command watchexec --project-origin . --ignore node_modules'
alias where='which'
alias wget='curl -L -O'

alias comp='node build/build-report-components.js && yarn eslint --fix report/renderer/components.js'
alias reportunit='yarn jest $(find report -iname "*-test.js" | grep -v axe)'
alias reportwatch='watchexec "node build/build-report-components.js && node build/build-report.js --psi && node build/build-sample-reports.js && echo $(date) && yarn eslint --fix report/renderer/components.js" && bash core/scripts/copy-util-commonjs.sh'

alias dig='dig +nocmd any +multiline +noall +answer'
alias cleanup_dsstore='find . -name "*.DS_Store" -type f -ls -delete'
alias xpraclient='xpra attach --video-scaling=off --desktop-scaling=off --dpi=96 --ssh=/usr/bin/ssh "ssh://glurp/:110"'
